name: deploy

on:
  push:
    branches:
      - demo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Use Google Cloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Info
      run: which python && python --version && which pip && pip --version && gcloud info
    - name: git submodules
      run: git submodule init && git submodule update
    - name: pip install
      run: pip install wheel && pip install --system -t lib -r requirements.txt
    - name: Install dependencies
      run: npm install --global bower polymer-cli
    - name: Bower dependencies
      run: bower install
    - name: Polymer Build
      run: polymer build
    - name: Client secrets
      run: echo '${{ secrets.OAUTH_CLIENT_SECRETS }}' > client_secrets.json
    - name: Deploy
      run: gcloud app deploy --project=${{ secrets.GCP_PROJECT_ID }}
